function scores = score_function(props, coeffs, isOMX)

I_raw               = props(1,:);
I_rel_nuke          = props(2,:);
I_rel_reg           = props(3,:);

eig_vec_z           = props(4,:);
eig_val_min         = props(5,:);
A_surf              = props(6,:);

A_reg               = props(7,:);
reg_ratio           = props(8,:);
min_area            = props(9,:);

kymo_param          = props(10,:);


if isOMX
    
    scores = coeffs(1) + ...
        ...
        coeffs(2) * A_surf + ...
        coeffs(3) * kymo_param + ...
        ...
        coeffs(4) * A_surf.^2 + ...
        coeffs(5) * kymo_param.^2 + ...
        ...
        coeffs(6) * A_surf .*      kymo_param;
    
else
    
    scores = coeffs(1) + ...
        ...
        coeffs(2) * I_raw + ...
        coeffs(3) * I_rel_nuke + ...
        coeffs(4) * I_rel_reg + ...
        coeffs(5) * eig_vec_z + ...
        coeffs(6) * A_surf + ...
        coeffs(7) * reg_ratio + ...
        coeffs(8) * kymo_param + ...
        ...
        coeffs(9) *  I_raw.^2 + ...
        coeffs(10) * I_rel_nuke.^2 + ...
        coeffs(11) * I_rel_reg.^2 + ...
        coeffs(12) * eig_vec_z.^2 + ...
        coeffs(13) * A_surf.^2 + ...
        coeffs(14) * reg_ratio.^2 + ...
        coeffs(15) * kymo_param.^2 + ...
        ...
        coeffs(16) * I_rel_reg .*   I_rel_nuke + ...
        coeffs(17) * eig_vec_z .*   I_rel_nuke + ...
        coeffs(18) * eig_val_min .* I_rel_nuke + ...
        coeffs(19) * kymo_param .*  I_rel_nuke + ...
        coeffs(20) * A_surf .*      I_rel_nuke + ...
        ...
        coeffs(21) * I_rel_reg .*   eig_vec_z + ...
        coeffs(22) * eig_val_min .* eig_vec_z + ...
        coeffs(23) * A_surf .*      eig_vec_z + ...
        coeffs(24) * kymo_param .*  eig_vec_z + ...
        ...
        coeffs(25) * I_rel_nuke .* eig_val_min + ...
        coeffs(26) * I_rel_reg .*  eig_val_min + ...
        coeffs(27) * A_surf .*     eig_val_min + ...
        coeffs(28) * kymo_param .* eig_val_min;
end

end



