function scores = score_function(props, coeffs)

I_raw         = props(1,:);
I_rel          = props(2,:);
I_rel_reg    = props(3,:);

eig_z         = props(4,:);

A_surf       = props(5,:);
A_reg        = props(6,:);

N_surf       = props(7,:);
A_surf_T    = props(8,:);
A_nuke      = props(9,:);
rad_nuke    = props(10,:);


scores = coeffs(1) + ...
...
           coeffs(2)*I_raw + ...
           coeffs(3)*I_rel + ...
           coeffs(4)*I_rel_reg + ...
           coeffs(5)*eig_z + ...
           coeffs(6)*A_surf + ...
           coeffs(7)*A_reg + ...
...
           coeffs(8)*I_raw.^2 + ...
           coeffs(9)*I_rel.^2 + ...
           coeffs(10)*I_rel_reg.^2 + ...
           coeffs(11)*eig_z.^2 + ...
           coeffs(12)*A_surf.^2 + ...
           coeffs(13)*A_reg.^2 + ...
...
           coeffs(14)*A_surf .* I_rel + ...
           coeffs(15)*eig_z .* I_rel + ...
           coeffs(16)*A_reg .* I_rel + ...
           coeffs(17)*I_raw .* I_rel + ...
           coeffs(18)*A_surf .* eig_z + ...
           coeffs(19)*A_reg .* eig_z + ...
           coeffs(20)*I_raw .* eig_z + ...
...
           coeffs(21)*A_surf./I_rel + ...
           coeffs(22)*eig_z./I_rel + ...
           coeffs(23)*eig_z./A_surf + ...
           coeffs(24)*I_raw./I_rel + ...
           coeffs(25)*I_rel./I_rel_reg + ...
           coeffs(26)*A_surf./A_reg + ...
...
           coeffs(27)*N_surf + ...
           coeffs(28)*A_surf_T + ...
           coeffs(29)*A_nuke + ...
           coeffs(30)*rad_nuke + ...
...
           coeffs(31)*N_surf.*A_surf + ...
           coeffs(32)*N_surf.*I_rel + ...
           coeffs(33)*rad_nuke.*A_surf + ...
           coeffs(34)*rad_nuke.*I_rel;
        
       

end



